server:
  port: 8082 #服务端口

itcast:
  item:
    url: http://127.0.0.1:8081/item/

spring:
  application:
    name: itcasst-microservice-order #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://itcast:itcast123@127.0.0.1:6868/eureka/,http://itcast:itcast123@127.0.0.1:6869/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
itcast-microservice-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #设置负载均衡为随机
